<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="stylesheets/create.css">
    <title>Nova Tasca</title>
</head>
<body>
    <h1>Nova Tasca</h1>
    <form method="post">
        <label for="nombre">Nom:</label>
        <input type="text" id="nom" name="nom" required>
        
        <label for="estat">Estat:</label>
        <select id="estat" name="estat" required>
            <option value="pendent">Pendent</option>
            <option value="en execució">En Execució</option>
            <option value="acabada">Acabada</option>
        </select>
        
        <label for="autor">Autor:</label>
        <input type="text" id="autor" name="autor" required>
        
        <div class="date-input">
            <label for="hora_ini">Hora inici:</label>
            <input type="date" id="hora_ini" name="hora_ini" required>
        </div>
        <div class="date-input">
            <label for="hora_fi">Hora fi:</label>
            <input type="date" id="hora_fi" name="hora_fi" required>
        </div>
        <input type="submit" value="Guardar Tasca">
    </form>
</body>
</html>