<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Nova Tasca</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        h1 {
            margin-bottom: 20px;
        }
        form {
            width: 80%;
            margin: 0 auto;
            text-align: left;
        }
        label {
            display: block;
            margin-bottom: 10px;
        }
        input[type="text"], select {
            width: 100%;
            padding: 8px;
            margin-bottom: 15px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box;
        }
        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }
       
    </style>
</head>
<body>
    <h1>Crear Nova Tasca</h1>
    <form method="post">
        <label for="nombre">Nom:</label>
        <input type="text" id="nom" name="nom" required>
        
        <label for="estat">Estat:</label>
        <select id="estat" name="estat" required>
            <option value="pendent">Pendent</option>
            <option value="en execució">En Execució</option>
            <option value="acabada">Acabada</option>
        </select>
        
        <label for="autor">Autor:</label>
        <input type="text" id="autor" name="autor" required>
        
        <input type="submit" value="Guardar Tasca">
    </form>
</body>
</html>