<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear nova tasca</title>
</head>
<body>
  <form method="post">
    <p>nom tasca:<input type="text" name= "nom"/></p>
    <p>hora inici:<input type="text" name="hora_ini" /></p>
    <p>hora fi:<input type="text" name="hora_fi" /></p>
    <p>autor:<input type="text" name="autor" /></p>
    <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="estat">
                    Estat
                </label>
            </div>
            <div class="md:w-2/3">
                <select name="estat" class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                    <option value="pendent" 
                        >Per iniciar</option>
                    <option value="en execució"  
                        >En curs</option>
                    <option value="acabada"  
                        >Completat</option>
                </select>
            </div>
            </div>
    <p><input type= "submit" value="enviar" /></p>
  </form>
</body>
</html>

