<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="stylesheets/delete.css">
    <title>Eliminar Tarea</title>
<head>
<?php
$oneTask = $this -> oneTask;
//print_r($oneTask);
?>
</head>
<body>
    <div class="confirmation-box">
        <h2>Segur que vols eliminar aquesta tasca?</h2>
        <div class="confirmation-buttons">
            <form method="post">
                <input type="hidden" name="id" value="<?php echo $id; ?>">
                <button type="submit" name="confirm_delete" class="delete">Eliminar</button>
            </form>
        
            <a href="./" class="return-button">Cancelar</a>
            </form>
        </div>
    </div>
</body>
</html>