<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="stylesheets/index.css">
    <title>Llista de Tasques</title>
</head>
<?php
$listTasks = $this -> data;
//print_r($listTasks);
?>

<body>
    <h1>Llista de Tasques</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Estat</th>
                <th>Autor</th>
                <th>Accions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($listTasks as $task): ?>
                <tr>
                    <td><?php echo $task->id; ?></td>
                    <td><?php echo $task->nom; ?></td>
                    <td><?php echo $task->estat; ?></td>
                    <td><?php echo $task->autor; ?></td>
                    <td>
                        <a href="readtask?id=<?php echo $task->id; ?>"><img src="images/view.png" alt="Mostrar" style="width: 20px; height: 20px";></a>    
                        <a href="update?id=<?php echo $task->id; ?>"><img src="images/edit.png" alt="Editar" style="width: 20px; height: 20px;"></a>
                        <a href="delete?id=<?php echo $task->id; ?>"><img src="images/delete.png" alt="Borrar" style="width: 20px; height: 20px";></a>
                        
                    </td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="5" style="text-align: center;">
                    <a href="create"><img src="images/add.png" alt="Nova Tasca" style="width: 20px; height: 20px;"></a>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>