<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<?php
$oneTask = $this -> oneTask;
//print_r($oneTask);
?>
<style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        h1 {
            margin-bottom: 20px;
        }
        .task-details {
            width: 80%;
            margin: 0 auto;
            text-align: left;
        }
        .task-details table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .task-details th, .task-details td {
            padding: 10px;
            border: 1px solid #ddd;
            text-align: center;
        }
        .task-details th {
            background-color: #f2f2f2;
        }
        .return-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            text-decoration: none;
        }
     </style>
</head>
<body>
    <h1>Detalls de la Tasca</h1>
    <div class="task-details">
        <table>
            <tr>
                <th>ID</th>
                <td><?php echo $oneTask->id; ?></td>
            </tr>
            <tr>
                <th>Nom</th>
                <td><?php echo $oneTask->nom; ?></td>
            </tr>
            <tr>
                <th>Estat</th>
                <td><?php echo $oneTask->estat; ?></td>
            </tr>
            <tr>
                <th>Autor</th>
                <td><?php echo $oneTask->autor;?></td>
            </tr>
            <tr>
                <th>Hora inici</th>
                <td><?php echo $oneTask->hora_ini;?></td>
            </tr>
            <tr>
                <th>Hora fi</th>
                <td><?php echo $oneTask->hora_fi;?></td>
            </tr>
        </table>
    </div>
    <a href="/" class="return-button">Lista</a>
</body>
</html>